BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS training_goals (
    training_goal_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT CHECK (description IS NULL OR char_length(description) <= 1000)
);

CREATE TABLE IF NOT EXISTS body_parts (
    body_part_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body_part_name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT CHECK (description IS NULL OR char_length(description) <= 1000)
);

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL CHECK (char_length(trim(name)) BETWEEN 1 AND 100),
    gender VARCHAR(20) CHECK (gender IS NULL OR gender IN ('Female', 'Male', 'Other')),
    age SMALLINT CHECK (age IS NULL OR age BETWEEN 13 AND 100),
    height_cm NUMERIC(5,2) CHECK (height_cm IS NULL OR height_cm BETWEEN 100 AND 250),
    training_experience VARCHAR(20) CHECK (
        training_experience IS NULL OR training_experience IN ('Beginner', 'Intermediate', 'Advanced')
    ),
    training_goal_id INTEGER REFERENCES training_goals(training_goal_id) ON DELETE RESTRICT,
    training_days_per_week SMALLINT CHECK (
        training_days_per_week IS NULL OR training_days_per_week BETWEEN 2 AND 6
    ),
    training_duration_minutes SMALLINT CHECK (
        training_duration_minutes IS NULL OR training_duration_minutes IN (30, 60, 90)
    ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_auth (
    auth_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE REFERENCES users(user_id) ON DELETE CASCADE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_sessions (
    user_session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    auth_id INTEGER NOT NULL REFERENCES user_auth(auth_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    CHECK (expires_at > created_at)
);

CREATE TABLE IF NOT EXISTS admins (
    user_id INTEGER PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_body_parts (
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    body_part_id INTEGER NOT NULL REFERENCES body_parts(body_part_id) ON DELETE RESTRICT,
    priority SMALLINT NOT NULL DEFAULT 1 CHECK (priority BETWEEN 1 AND 8),
    PRIMARY KEY (user_id, body_part_id),
    UNIQUE (user_id, priority)
);

CREATE TABLE IF NOT EXISTS exercises (
    exercise_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_name VARCHAR(120) NOT NULL UNIQUE CHECK (char_length(trim(exercise_name)) BETWEEN 1 AND 120),
    body_part_id INTEGER NOT NULL REFERENCES body_parts(body_part_id) ON DELETE RESTRICT,
    difficulty_level VARCHAR(20) NOT NULL CHECK (
        difficulty_level IN ('Beginner', 'Intermediate', 'Advanced')
    ),
    equipment VARCHAR(100),
    description TEXT NOT NULL CHECK (char_length(description) BETWEEN 1 AND 4000),
    image_url TEXT CHECK (image_url IS NULL OR char_length(image_url) <= 2048),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS workout_plans (
    workout_plan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    plan_name VARCHAR(120) NOT NULL CHECK (char_length(trim(plan_name)) BETWEEN 1 AND 120),
    training_goal_id INTEGER NOT NULL REFERENCES training_goals(training_goal_id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    experience_snapshot VARCHAR(20) NOT NULL CHECK (
        experience_snapshot IN ('Beginner', 'Intermediate', 'Advanced')
    ),
    duration_minutes SMALLINT NOT NULL CHECK (duration_minutes IN (30, 60, 90))
);

CREATE TABLE IF NOT EXISTS plan_days (
    plan_day_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_plan_id INTEGER NOT NULL REFERENCES workout_plans(workout_plan_id) ON DELETE CASCADE,
    day_number SMALLINT NOT NULL CHECK (day_number BETWEEN 1 AND 6),
    day_title VARCHAR(120) NOT NULL CHECK (char_length(trim(day_title)) BETWEEN 1 AND 120),
    UNIQUE (workout_plan_id, day_number)
);

CREATE TABLE IF NOT EXISTS plan_exercises (
    plan_exercise_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_day_id INTEGER NOT NULL REFERENCES plan_days(plan_day_id) ON DELETE CASCADE,
    exercise_id INTEGER NOT NULL REFERENCES exercises(exercise_id) ON DELETE RESTRICT,
    exercise_order SMALLINT NOT NULL CHECK (exercise_order BETWEEN 1 AND 6),
    target_sets SMALLINT NOT NULL CHECK (target_sets BETWEEN 1 AND 10),
    target_reps SMALLINT NOT NULL CHECK (target_reps BETWEEN 1 AND 50),
    rest_seconds SMALLINT NOT NULL CHECK (rest_seconds BETWEEN 0 AND 300),
    UNIQUE (plan_day_id, exercise_order),
    UNIQUE (plan_day_id, exercise_id)
);

CREATE TABLE IF NOT EXISTS workout_sessions (
    workout_session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'in_progress' CHECK (
        status IN ('in_progress', 'completed', 'cancelled')
    ),
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMPTZ,
    notes TEXT CHECK (notes IS NULL OR char_length(notes) <= 1000),
    CHECK (
        (status = 'in_progress' AND ended_at IS NULL)
        OR (status IN ('completed', 'cancelled') AND ended_at IS NOT NULL AND ended_at >= started_at)
    )
);

CREATE TABLE IF NOT EXISTS workout_sets (
    workout_set_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_session_id INTEGER NOT NULL REFERENCES workout_sessions(workout_session_id) ON DELETE CASCADE,
    exercise_id INTEGER NOT NULL REFERENCES exercises(exercise_id) ON DELETE RESTRICT,
    set_number SMALLINT NOT NULL CHECK (set_number BETWEEN 1 AND 100),
    weight_kg NUMERIC(6,2) NOT NULL CHECK (weight_kg BETWEEN 0 AND 999.99),
    reps SMALLINT NOT NULL CHECK (reps BETWEEN 1 AND 999),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (workout_session_id, exercise_id, set_number)
);

CREATE TABLE IF NOT EXISTS body_records (
    body_record_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    record_date DATE NOT NULL,
    weight_kg NUMERIC(5,2) NOT NULL CHECK (weight_kg BETWEEN 20 AND 500),
    notes TEXT CHECK (notes IS NULL OR char_length(notes) <= 1000),
    UNIQUE (user_id, record_date)
);

CREATE TABLE IF NOT EXISTS workout_session_plans (
    workout_session_id INTEGER PRIMARY KEY REFERENCES workout_sessions(workout_session_id) ON DELETE CASCADE,
    plan_day_id INTEGER NOT NULL REFERENCES plan_days(plan_day_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_workout_sessions_user_active
    ON workout_sessions(user_id) WHERE status = 'in_progress';
CREATE INDEX IF NOT EXISTS idx_exercises_recommendation
    ON exercises(body_part_id, difficulty_level, is_active);
CREATE INDEX IF NOT EXISTS idx_workout_plans_user
    ON workout_plans(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_workout_sessions_user_started
    ON workout_sessions(user_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_workout_sets_exercise
    ON workout_sets(exercise_id, workout_session_id);
CREATE INDEX IF NOT EXISTS idx_body_records_user_date
    ON body_records(user_id, record_date DESC);

COMMIT;
