"""initial schema

Revision ID: 8da40fe7d247
Revises:
Create Date: 2026-09-16 10:00:07.033064
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8da40fe7d247"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "body_parts",
        sa.Column("body_part_id", sa.SmallInteger(), nullable=False),
        sa.Column("body_part_code", sa.String(length=30), nullable=False),
        sa.Column("name_en", sa.String(length=50), nullable=False),
        sa.Column("name_zh", sa.String(length=20), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.CheckConstraint("display_order > 0", name="ck_body_part_order"),
        sa.PrimaryKeyConstraint("body_part_id"),
        sa.UniqueConstraint("body_part_code"),
        sa.UniqueConstraint("display_order"),
        sa.UniqueConstraint("name_en"),
        sa.UniqueConstraint("name_zh"),
    )
    op.create_table(
        "training_goals",
        sa.Column("training_goal_id", sa.SmallInteger(), nullable=False),
        sa.Column("goal_code", sa.String(length=30), nullable=False),
        sa.Column("goal_name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_sets", sa.SmallInteger(), nullable=False),
        sa.Column("default_reps", sa.SmallInteger(), nullable=False),
        sa.Column("default_rest_seconds", sa.Integer(), nullable=False),
        sa.CheckConstraint("default_reps BETWEEN 1 AND 30", name="ck_goal_default_reps"),
        sa.CheckConstraint("default_rest_seconds BETWEEN 15 AND 300", name="ck_goal_default_rest"),
        sa.CheckConstraint("default_sets BETWEEN 1 AND 6", name="ck_goal_default_sets"),
        sa.PrimaryKeyConstraint("training_goal_id"),
        sa.UniqueConstraint("goal_code"),
    )
    op.create_table(
        "exercises",
        sa.Column(
            "exercise_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("exercise_name", sa.String(length=120), nullable=False),
        sa.Column("body_part_id", sa.SmallInteger(), nullable=False),
        sa.Column("difficulty_level", sa.String(length=20), nullable=False),
        sa.Column("equipment", sa.String(length=80), nullable=False),
        sa.Column("movement_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "difficulty_level IN ('beginner','intermediate','advanced')",
            name="ck_exercise_difficulty",
        ),
        sa.CheckConstraint(
            "movement_type IN ('compound','isolation')", name="ck_exercise_movement_type"
        ),
        sa.ForeignKeyConstraint(["body_part_id"], ["body_parts.body_part_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("exercise_id"),
    )
    op.create_index("ix_exercises_equipment", "exercises", ["equipment", "is_active"], unique=False)
    op.create_index(
        "ix_exercises_recommendation",
        "exercises",
        ["body_part_id", "difficulty_level", "is_active"],
        unique=False,
    )
    op.create_index(
        "uq_exercises_name_ci", "exercises", [sa.text("lower(exercise_name)")], unique=True
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column("age", sa.SmallInteger(), nullable=False),
        sa.Column("height_cm", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("training_experience", sa.String(length=20), nullable=False),
        sa.Column("training_goal_id", sa.SmallInteger(), nullable=False),
        sa.Column("training_days_per_week", sa.SmallInteger(), nullable=False),
        sa.Column("training_duration_minutes", sa.SmallInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "gender IS NULL OR gender IN ('male','female','non_binary','prefer_not_to_say')",
            name="ck_user_gender",
        ),
        sa.CheckConstraint(
            "training_experience IN ('beginner','intermediate','advanced')",
            name="ck_user_experience",
        ),
        sa.CheckConstraint("age BETWEEN 13 AND 100", name="ck_user_age"),
        sa.CheckConstraint("height_cm BETWEEN 50 AND 300", name="ck_user_height"),
        sa.CheckConstraint("training_days_per_week IN (2,3,4,5,6)", name="ck_user_days"),
        sa.CheckConstraint("training_duration_minutes IN (30,60,90)", name="ck_user_duration"),
        sa.ForeignKeyConstraint(
            ["training_goal_id"], ["training_goals.training_goal_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index("ix_users_training_goal_id", "users", ["training_goal_id"], unique=False)
    op.create_table(
        "body_records",
        sa.Column(
            "body_record_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("recorded_on", sa.Date(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("weight_kg BETWEEN 20 AND 500", name="ck_body_record_weight"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("body_record_id"),
        sa.UniqueConstraint("user_id", "recorded_on", name="uq_body_record_day"),
    )
    op.create_table(
        "user_body_parts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("body_part_id", sa.SmallInteger(), nullable=False),
        sa.Column(
            "selected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["body_part_id"], ["body_parts.body_part_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "body_part_id"),
    )
    op.create_index(
        "ix_user_body_parts_reverse", "user_body_parts", ["body_part_id", "user_id"], unique=False
    )
    op.create_table(
        "workout_plans",
        sa.Column(
            "plan_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("training_goal_id", sa.SmallInteger(), nullable=False),
        sa.Column("plan_name", sa.String(length=120), nullable=False),
        sa.Column("training_days_per_week", sa.SmallInteger(), nullable=False),
        sa.Column("training_duration_minutes", sa.SmallInteger(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('generated','active','archived')", name="ck_plan_status"),
        sa.CheckConstraint("training_days_per_week IN (2,3,4,5,6)", name="ck_plan_days"),
        sa.CheckConstraint("training_duration_minutes IN (30,60,90)", name="ck_plan_duration"),
        sa.ForeignKeyConstraint(
            ["training_goal_id"], ["training_goals.training_goal_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("plan_id"),
    )
    op.create_index(
        "uq_workout_plans_one_active",
        "workout_plans",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
        sqlite_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "ix_workout_plans_user_generated",
        "workout_plans",
        ["user_id", sa.text("generated_at DESC")],
        unique=False,
    )
    op.create_table(
        "workout_sessions",
        sa.Column(
            "session_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status <> 'completed' OR ended_at IS NOT NULL", name="ck_completed_session_end"
        ),
        sa.CheckConstraint(
            "status IN ('in_progress','completed','cancelled')", name="ck_session_status"
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at", name="ck_session_end_after_start"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        "ix_sessions_user_status", "workout_sessions", ["user_id", "status"], unique=False
    )
    op.create_index(
        "ix_sessions_user_started",
        "workout_sessions",
        ["user_id", sa.text("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "plan_days",
        sa.Column(
            "plan_day_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("plan_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("day_number", sa.SmallInteger(), nullable=False),
        sa.Column("day_name", sa.String(length=100), nullable=False),
        sa.Column("focus_summary", sa.String(length=150), nullable=False),
        sa.CheckConstraint("day_number BETWEEN 1 AND 6", name="ck_plan_day_number"),
        sa.ForeignKeyConstraint(["plan_id"], ["workout_plans.plan_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("plan_day_id"),
        sa.UniqueConstraint("plan_id", "day_number", name="uq_plan_day_number"),
    )
    op.create_table(
        "workout_sets",
        sa.Column(
            "workout_set_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "session_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "exercise_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("set_order", sa.SmallInteger(), nullable=False),
        sa.Column("set_number", sa.SmallInteger(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("reps", sa.SmallInteger(), nullable=False),
        sa.Column("is_warmup", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "logged_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("reps BETWEEN 1 AND 100", name="ck_workout_set_reps"),
        sa.CheckConstraint("set_number > 0", name="ck_workout_set_number"),
        sa.CheckConstraint("set_order > 0", name="ck_workout_set_order"),
        sa.CheckConstraint("weight_kg >= 0", name="ck_workout_set_weight"),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.exercise_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["workout_sessions.session_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("workout_set_id"),
        sa.UniqueConstraint(
            "session_id", "exercise_id", "set_number", name="uq_session_exercise_set"
        ),
        sa.UniqueConstraint("session_id", "set_order", name="uq_workout_set_order"),
    )
    op.create_index(
        "ix_workout_sets_exercise_logged",
        "workout_sets",
        ["exercise_id", "logged_at"],
        unique=False,
    )
    op.create_table(
        "plan_exercises",
        sa.Column(
            "plan_exercise_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "plan_day_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "exercise_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("exercise_order", sa.SmallInteger(), nullable=False),
        sa.Column("target_sets", sa.SmallInteger(), nullable=False),
        sa.Column("target_reps", sa.SmallInteger(), nullable=False),
        sa.Column("rest_seconds", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("exercise_order > 0", name="ck_plan_exercise_order"),
        sa.CheckConstraint("rest_seconds BETWEEN 15 AND 300", name="ck_plan_exercise_rest"),
        sa.CheckConstraint("target_reps BETWEEN 1 AND 30", name="ck_plan_exercise_reps"),
        sa.CheckConstraint("target_sets BETWEEN 1 AND 6", name="ck_plan_exercise_sets"),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.exercise_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["plan_day_id"], ["plan_days.plan_day_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("plan_exercise_id"),
        sa.UniqueConstraint("plan_day_id", "exercise_id", name="uq_plan_day_exercise"),
        sa.UniqueConstraint("plan_day_id", "exercise_order", name="uq_plan_exercise_order"),
    )
    op.create_index(
        "ix_plan_exercises_exercise_id", "plan_exercises", ["exercise_id"], unique=False
    )
    op.create_table(
        "session_plan_days",
        sa.Column(
            "session_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "plan_day_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.ForeignKeyConstraint(["plan_day_id"], ["plan_days.plan_day_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["workout_sessions.session_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        "ix_session_plan_days_plan_day", "session_plan_days", ["plan_day_id"], unique=False
    )

    if op.get_bind().dialect.name == "postgresql":
        op.execute("""
            CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
            BEGIN
                NEW.updated_at = CURRENT_TIMESTAMP;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
        """)
        op.execute("""
            CREATE TRIGGER users_set_updated_at
            BEFORE UPDATE ON users
            FOR EACH ROW EXECUTE FUNCTION set_updated_at()
        """)
        op.execute("""
            CREATE TRIGGER exercises_set_updated_at
            BEFORE UPDATE ON exercises
            FOR EACH ROW EXECUTE FUNCTION set_updated_at()
        """)
        op.execute("""
            CREATE FUNCTION validate_session_plan_day_owner() RETURNS trigger AS $$
            DECLARE
                session_user uuid;
                plan_user uuid;
            BEGIN
                SELECT user_id INTO session_user
                FROM workout_sessions WHERE session_id = NEW.session_id;

                SELECT wp.user_id INTO plan_user
                FROM plan_days pd
                JOIN workout_plans wp ON wp.plan_id = pd.plan_id
                WHERE pd.plan_day_id = NEW.plan_day_id;

                IF session_user IS DISTINCT FROM plan_user THEN
                    RAISE EXCEPTION 'Session and Plan Day must belong to the same user';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
        """)
        op.execute("""
            CREATE CONSTRAINT TRIGGER session_plan_day_owner
            AFTER INSERT OR UPDATE ON session_plan_days
            DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION validate_session_plan_day_owner()
        """)
        op.execute("""
            CREATE FUNCTION validate_active_plan_day_count() RETURNS trigger AS $$
            BEGIN
                IF NEW.status = 'active' AND (
                    SELECT COUNT(*) FROM plan_days WHERE plan_id = NEW.plan_id
                ) <> NEW.training_days_per_week THEN
                    RAISE EXCEPTION 'Active plan day count must match training_days_per_week';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
        """)
        op.execute("""
            CREATE CONSTRAINT TRIGGER active_plan_day_count
            AFTER INSERT OR UPDATE ON workout_plans
            DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION validate_active_plan_day_count()
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS active_plan_day_count ON workout_plans")
        op.execute("DROP FUNCTION IF EXISTS validate_active_plan_day_count()")
        op.execute("DROP TRIGGER IF EXISTS session_plan_day_owner ON session_plan_days")
        op.execute("DROP FUNCTION IF EXISTS validate_session_plan_day_owner()")
        op.execute("DROP TRIGGER IF EXISTS exercises_set_updated_at ON exercises")
        op.execute("DROP TRIGGER IF EXISTS users_set_updated_at ON users")
        op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    op.drop_index("ix_session_plan_days_plan_day", table_name="session_plan_days")
    op.drop_table("session_plan_days")
    op.drop_index("ix_plan_exercises_exercise_id", table_name="plan_exercises")
    op.drop_table("plan_exercises")
    op.drop_index("ix_workout_sets_exercise_logged", table_name="workout_sets")
    op.drop_table("workout_sets")
    op.drop_table("plan_days")
    op.drop_index("ix_sessions_user_started", table_name="workout_sessions")
    op.drop_index("ix_sessions_user_status", table_name="workout_sessions")
    op.drop_table("workout_sessions")
    op.drop_index("ix_workout_plans_user_generated", table_name="workout_plans")
    op.drop_index(
        "uq_workout_plans_one_active",
        table_name="workout_plans",
        postgresql_where=sa.text("status = 'active'"),
        sqlite_where=sa.text("status = 'active'"),
    )
    op.drop_table("workout_plans")
    op.drop_index("ix_user_body_parts_reverse", table_name="user_body_parts")
    op.drop_table("user_body_parts")
    op.drop_table("body_records")
    op.drop_index("ix_users_training_goal_id", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_exercises_recommendation", table_name="exercises")
    op.drop_index("ix_exercises_equipment", table_name="exercises")
    op.drop_index("uq_exercises_name_ci", table_name="exercises")
    op.drop_table("exercises")
    op.drop_table("training_goals")
    op.drop_table("body_parts")
    # ### end Alembic commands ###
